In [18]:
import numpy as np

a= np.array([1,2, 3, 4])
b= np.array([[1,2, 3], [4,5, 6]])
np.concatenate((a, np.ravel(b)))

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np

mask = np.array([-1e5, 0, -1e5])

np.random.choice([1,2,3], p=np.where(mask == -1e5, 0.0, 1.0 / (3 - np.count_nonzero(mask))))

np.int64(2)

In [12]:
a = {3: 2}


In [13]:


a[np.int64(3)]

2

In [1]:
import gymnasium as gym
import kymnasium as kym

env = gym.make('kymnasium/ZeldaAdventure-Stage-3', render_mode='rgb_array')
obs, _ = env.reset()
sword = dict()
objects = dict()

tiles = obs['tiles']

for row in tiles:
    x, y, obj_id, prop = row
    if obj_id in (7, 11, 12, 13):
        objects[int(y * 36 + x)] = int(prop)
    elif obj_id == 6:
        sword[int(prop)] = int(y * 36 + x)


D:\Projects\kymnasium\.venv\Lib\site-packages\pygame\pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream, resource_exists


In [2]:
objects

{184: 2,
 400: 2,
 616: 2,
 832: 2,
 941: 3,
 443: 5,
 418: 5,
 455: 1,
 1038: 3,
 392: 6,
 608: 6,
 824: 6,
 1040: 6,
 501: 6,
 717: 6,
 933: 6}

In [65]:
sword

{2: 1084, 5: 514, 1: 559, 6: 319, 3: 1221}

In [55]:
a[3]

array([-0.29797084,  0.03271727,  1.49255201, -1.40281649,  1.12556886,
       -0.75856452,  0.16121226,  0.83522295, -0.55898657, -0.12916731])

In [60]:
import json

with open('./test.pkl', 'w') as f:
    json.dump(a, f)

TypeError: Object of type ActionValue is not JSON serializable

In [57]:
with open('./test.pkl', 'r') as f:
    b = json.load(f)


In [59]:
len(b)

1

In [41]:
import json


gen = np.random.default_rng(42)
with open('./test.json', 'w') as f:
    json.dump({'gen': gen.bit_generator.state}, f)
with open('./test.json', 'r') as f:
    b = json.load(f)
print(gen.random())
b

0.7739560485559633


{'gen': {'bit_generator': 'PCG64',
  'state': {'state': 274674114334540486603088602300644985544,
   'inc': 332724090758049132448979897138935081983},
  'has_uint32': 0,
  'uinteger': 0}}

In [42]:
gen = np.random.default_rng(42)
gen.bit_generator.state = b['gen']

In [44]:
gen.random()

0.7739560485559633

In [35]:
b

{3: array([ 1.02642116, -0.09429909, -0.16294608, -1.33407602,  0.09712936,
       -0.60443763,  0.34346422,  2.03524772, -1.72615003, -1.10250042])}

In [15]:
from collections import UserDict


class HashableArray:
    def __init__(self, array):
        self.array = array
        self.array.flags.writeable = False

    def __eq__(self, other):
        return np.array_equal(self.array, other.array)

    def __hash__(self):
        return hash(self.array.tobytes())


class ActionValueDict(UserDict):
    def __init__(self, n_actions: int, seed: int = None, scale: float = 1.0, offset: float = 0.0):
        super().__init__()
        self._n_actions = n_actions
        self._random = np.random.default_rng(seed)
        self._scale = scale
        self._offset = offset

    def __setitem__(self, key: np.ndarray, value: np.ndarray):
        hash_key = HashableArray(key)
        self.data[hash_key] = value

    def __getitem__(self, key: np.ndarray):
        hash_key = HashableArray(key)
        if hash_key not in self.data:
            init_value = self._random.normal(size=(self._n_actions,)) * self._scale + self._offset
            self.data[hash_key] = init_value
        return self.data[hash_key]


action_value = ActionValueDict(n_actions=10)
action_value[np.array([1,2,3])]


array([-0.74050065, -1.86981632,  0.86707   ,  1.74656749, -1.77929349,
       -1.035663  , -0.82145489, -0.23974714,  0.83757148, -0.07688776])

In [10]:
def test():
    a = dict(a=1, b=2)
    if len(a) < 1:
        for key in a:
            yield key, a[key]

for key, value in test():
    print(key, value)



In [6]:
a

{'b': 2}